AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CloudFormation Macro to create Systems Manager SecureString Params

Globals:
  Function:
    Timeout: 3

Parameters:
  LogGroupName:
    Type: String
    Default: ""

Conditions:
  UseDefaultLogGroup:
    Fn::Equals:
      - Ref: LogGroupName
      - ""

Resources:
  CfnMacroFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ssm_securestring_cfn_macro/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Role:
        Fn::GetAtt:
          - CfnMacroRole
          - Arn

  CfnMacroRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: CreateLogsPermission
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
      RoleName:
        Fn::Sub: "${AWS::StackName}-role"

  CfnMacro:
    Type: AWS::CloudFormation::Macro
    Properties:
      FunctionName:
        Fn::GetAtt:
          - CfnMacroFunction
          - Arn
      LogGroupName:
        Fn::If:
          - UseDefaultLogGroup
          - Ref: AWS::NoValue
          - Ref: LogGroupName
      Name:
        Fn::Sub: "${AWS::StackName}-macro"

Outputs:
  FunctionName:
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-function-name"
    Value:
      Ref: CfnMacroFunction

  FunctionArn:
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-function-arn"
    Value:
      Fn::GetAtt:
        - CfnMacroFunction
        - Arn

  RoleArn:
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-role-arn"
    Value:
      Fn::GetAtt:
        - CfnMacroRole
        - Arn

  MacroName:
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-macro-name"
    Value:
      Ref: CfnMacro
