AWSTemplateFormatVersion: '2010-09-09'
Description: Example of invoking CloudFormation Macro to create SSM SecureString Parameter


Resources:
  SSMSecureStringParam:
    Type: AWS::CloudFormation::Macro
    Properties:
      FunctionName:
        Fn::ImportValue: "ssm-securestring-cfn-macro-function-arn"
      Name:
        Fn::Sub: "${AWS::StackName}-ssm-securestring-cfn-macro"

Outputs:
  FunctionArn:
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-function-arn"
    Value:
      Fn::GetAtt:
        - CfnMacro
        - Arn

  RoleArn:
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-role-arn"
    Value:
      Fn::GetAtt:
        - CfnMacroRole
        - Arn

