name: Commit Status Check Workflow

on: [push]

jobs:
  cloudformation-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Linter
        uses: actions/checkout@v3

      - name: Setup Cloud Formation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2

      - name: Print the Cloud Formation Linter Version & run Linter.
        run: cfn-lint --version

      - name: Lint SAM Template
        run: cfn-lint -t template.yaml

      - name: Lint Parameterized SSM Parameter Template
        run: cfn-lint -t ssm-parameter.yaml

