name: Auto deployment from main branch workflow

on:
  push:
    branches:
      - main

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  sam-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}"
          aws-region: "${{ secrets.AWS_REGION }}"

      - name: Build SAM Project
        run: |
          mkdir layer
          cp ssm_securestring_cfn_macro/requirements.txt layer/requirements.txt
          cd layer
          pip3 install --target . -r requirements.txt
          cd ..
          sam build

      - name: Deploy SAM Project
        run: sam deploy --stack-name "gh-ssm-securestring-cfn-macro" --template-file ".aws-sam/build/template.yaml" --s3-bucket "${{ secrets.CLOUDFORMATION_PACKAGES_BUCKET }}" --s3-prefix "gh-ssm-securestring-cfn-macro" --region "${{ secrets.AWS_REGION }}"  --capabilities "CAPABILITY_NAMED_IAM" --no-confirm-changeset --no-fail-on-empty-changeset --parameter-overrides "LogGroupName=${{ secrets.CLOUDFORMATION_MACROS_LOG_GROUP }}"



